package com.example.demo.entity;

import java.io.Serializable;

public class Animal implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.actscope
     *
     * @mbggenerated
     */
    private String actscope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table animal
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.id
     *
     * @return the value of animal.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.id
     *
     * @param id the value for animal.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.name
     *
     * @return the value of animal.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.name
     *
     * @param name the value for animal.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.type
     *
     * @return the value of animal.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.type
     *
     * @param type the value for animal.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.actscope
     *
     * @return the value of animal.actscope
     *
     * @mbggenerated
     */
    public String getActscope() {
        return actscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.actscope
     *
     * @param actscope the value for animal.actscope
     *
     * @mbggenerated
     */
    public void setActscope(String actscope) {
        this.actscope = actscope == null ? null : actscope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", actscope=").append(actscope);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}