package com.example.demo.entity;

import java.io.Serializable;

public class Course implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.curName
     *
     * @mbggenerated
     */
    private String curname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.credit
     *
     * @mbggenerated
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.nowRemain
     *
     * @mbggenerated
     */
    private Integer nowremain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.maxRemain
     *
     * @mbggenerated
     */
    private Integer maxremain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teaName
     *
     * @mbggenerated
     */
    private String teaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.field
     *
     * @mbggenerated
     */
    private Integer field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.day
     *
     * @mbggenerated
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.startWeek
     *
     * @mbggenerated
     */
    private Integer startweek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.endWeek
     *
     * @mbggenerated
     */
    private Integer endweek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.weeklyTimes
     *
     * @mbggenerated
     */
    private Integer weeklytimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.startSection
     *
     * @mbggenerated
     */
    private Integer startsection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.endSection
     *
     * @mbggenerated
     */
    private Integer endsection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.curName
     *
     * @return the value of course.curName
     *
     * @mbggenerated
     */
    public String getCurname() {
        return curname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.curName
     *
     * @param curname the value for course.curName
     *
     * @mbggenerated
     */
    public void setCurname(String curname) {
        this.curname = curname == null ? null : curname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.credit
     *
     * @return the value of course.credit
     *
     * @mbggenerated
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.credit
     *
     * @param credit the value for course.credit
     *
     * @mbggenerated
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.nowRemain
     *
     * @return the value of course.nowRemain
     *
     * @mbggenerated
     */
    public Integer getNowremain() {
        return nowremain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.nowRemain
     *
     * @param nowremain the value for course.nowRemain
     *
     * @mbggenerated
     */
    public void setNowremain(Integer nowremain) {
        this.nowremain = nowremain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.maxRemain
     *
     * @return the value of course.maxRemain
     *
     * @mbggenerated
     */
    public Integer getMaxremain() {
        return maxremain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.maxRemain
     *
     * @param maxremain the value for course.maxRemain
     *
     * @mbggenerated
     */
    public void setMaxremain(Integer maxremain) {
        this.maxremain = maxremain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teaName
     *
     * @return the value of course.teaName
     *
     * @mbggenerated
     */
    public String getTeaname() {
        return teaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teaName
     *
     * @param teaname the value for course.teaName
     *
     * @mbggenerated
     */
    public void setTeaname(String teaname) {
        this.teaname = teaname == null ? null : teaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.field
     *
     * @return the value of course.field
     *
     * @mbggenerated
     */
    public Integer getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.field
     *
     * @param field the value for course.field
     *
     * @mbggenerated
     */
    public void setField(Integer field) {
        this.field = field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.day
     *
     * @return the value of course.day
     *
     * @mbggenerated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.day
     *
     * @param day the value for course.day
     *
     * @mbggenerated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.startWeek
     *
     * @return the value of course.startWeek
     *
     * @mbggenerated
     */
    public Integer getStartweek() {
        return startweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.startWeek
     *
     * @param startweek the value for course.startWeek
     *
     * @mbggenerated
     */
    public void setStartweek(Integer startweek) {
        this.startweek = startweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.endWeek
     *
     * @return the value of course.endWeek
     *
     * @mbggenerated
     */
    public Integer getEndweek() {
        return endweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.endWeek
     *
     * @param endweek the value for course.endWeek
     *
     * @mbggenerated
     */
    public void setEndweek(Integer endweek) {
        this.endweek = endweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.weeklyTimes
     *
     * @return the value of course.weeklyTimes
     *
     * @mbggenerated
     */
    public Integer getWeeklytimes() {
        return weeklytimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.weeklyTimes
     *
     * @param weeklytimes the value for course.weeklyTimes
     *
     * @mbggenerated
     */
    public void setWeeklytimes(Integer weeklytimes) {
        this.weeklytimes = weeklytimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.startSection
     *
     * @return the value of course.startSection
     *
     * @mbggenerated
     */
    public Integer getStartsection() {
        return startsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.startSection
     *
     * @param startsection the value for course.startSection
     *
     * @mbggenerated
     */
    public void setStartsection(Integer startsection) {
        this.startsection = startsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.endSection
     *
     * @return the value of course.endSection
     *
     * @mbggenerated
     */
    public Integer getEndsection() {
        return endsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.endSection
     *
     * @param endsection the value for course.endSection
     *
     * @mbggenerated
     */
    public void setEndsection(Integer endsection) {
        this.endsection = endsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", curname=").append(curname);
        sb.append(", credit=").append(credit);
        sb.append(", nowremain=").append(nowremain);
        sb.append(", maxremain=").append(maxremain);
        sb.append(", teaname=").append(teaname);
        sb.append(", field=").append(field);
        sb.append(", day=").append(day);
        sb.append(", startweek=").append(startweek);
        sb.append(", endweek=").append(endweek);
        sb.append(", weeklytimes=").append(weeklytimes);
        sb.append(", startsection=").append(startsection);
        sb.append(", endsection=").append(endsection);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}