package com.example.demo.entity;

import lombok.Data;

import java.io.Serializable;

@Data
public class StuCou implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_cou.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_cou.cid
     *
     * @mbggenerated
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_cou.task1
     *
     * @mbggenerated
     */
    private Integer task1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_cou.task2
     *
     * @mbggenerated
     */
    private Integer task2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_cou.task3
     *
     * @mbggenerated
     */
    private Integer task3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_cou.finalScore
     *
     * @mbggenerated
     */
    private Integer finalscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_cou.total
     *
     * @mbggenerated
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stu_cou
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_cou.sid
     *
     * @return the value of stu_cou.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_cou.sid
     *
     * @param sid the value for stu_cou.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_cou.cid
     *
     * @return the value of stu_cou.cid
     *
     * @mbggenerated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_cou.cid
     *
     * @param cid the value for stu_cou.cid
     *
     * @mbggenerated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_cou.task1
     *
     * @return the value of stu_cou.task1
     *
     * @mbggenerated
     */
    public Integer getTask1() {
        return task1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_cou.task1
     *
     * @param task1 the value for stu_cou.task1
     *
     * @mbggenerated
     */
    public void setTask1(Integer task1) {
        this.task1 = task1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_cou.task2
     *
     * @return the value of stu_cou.task2
     *
     * @mbggenerated
     */
    public Integer getTask2() {
        return task2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_cou.task2
     *
     * @param task2 the value for stu_cou.task2
     *
     * @mbggenerated
     */
    public void setTask2(Integer task2) {
        this.task2 = task2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_cou.task3
     *
     * @return the value of stu_cou.task3
     *
     * @mbggenerated
     */
    public Integer getTask3() {
        return task3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_cou.task3
     *
     * @param task3 the value for stu_cou.task3
     *
     * @mbggenerated
     */
    public void setTask3(Integer task3) {
        this.task3 = task3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_cou.finalScore
     *
     * @return the value of stu_cou.finalScore
     *
     * @mbggenerated
     */
    public Integer getFinalscore() {
        return finalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_cou.finalScore
     *
     * @param finalscore the value for stu_cou.finalScore
     *
     * @mbggenerated
     */
    public void setFinalscore(Integer finalscore) {
        this.finalscore = finalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_cou.total
     *
     * @return the value of stu_cou.total
     *
     * @mbggenerated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_cou.total
     *
     * @param total the value for stu_cou.total
     *
     * @mbggenerated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_cou
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", cid=").append(cid);
        sb.append(", task1=").append(task1);
        sb.append(", task2=").append(task2);
        sb.append(", task3=").append(task3);
        sb.append(", finalscore=").append(finalscore);
        sb.append(", total=").append(total);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}