package com.example.demo.entity;

import java.io.Serializable;
import java.util.Date;

public class Transaction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.tm
     *
     * @mbggenerated
     */
    private Date tm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.hash
     *
     * @mbggenerated
     */
    private String hash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transaction
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.id
     *
     * @return the value of transaction.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.id
     *
     * @param id the value for transaction.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.uid
     *
     * @return the value of transaction.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.uid
     *
     * @param uid the value for transaction.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.aid
     *
     * @return the value of transaction.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.aid
     *
     * @param aid the value for transaction.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.money
     *
     * @return the value of transaction.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.money
     *
     * @param money the value for transaction.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.tm
     *
     * @return the value of transaction.tm
     *
     * @mbggenerated
     */
    public Date getTm() {
        return tm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.tm
     *
     * @param tm the value for transaction.tm
     *
     * @mbggenerated
     */
    public void setTm(Date tm) {
        this.tm = tm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.hash
     *
     * @return the value of transaction.hash
     *
     * @mbggenerated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.hash
     *
     * @param hash the value for transaction.hash
     *
     * @mbggenerated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", aid=").append(aid);
        sb.append(", money=").append(money);
        sb.append(", tm=").append(tm);
        sb.append(", hash=").append(hash);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}