package com.example.demo.dao;

import com.example.demo.entity.Animal;
import java.util.List;

public interface AnimalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int insert(Animal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    Animal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    List<Animal> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Animal record);
}