package com.example.demo.dao;

import com.example.demo.entity.Flow;
import java.util.List;

public interface FlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow
     *
     * @mbggenerated
     */
    int insert(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow
     *
     * @mbggenerated
     */
    Flow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow
     *
     * @mbggenerated
     */
    List<Flow> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Flow record);
}