package com.example.demo.dao;

import com.example.demo.entity.StuCou;
import java.util.List;

public interface StuCouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_cou
     *
     * @mbggenerated
     */
    int insert(StuCou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_cou
     *
     * @mbggenerated
     */
    List<StuCou> selectAll();
}